name: Deploy Resource Group Via Terraform

on:
  push:
    branches:
      - master

jobs:
  login-and-deploy-to-Azure:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_CREDENTIALS_AS_GITHUB_SECRET }}

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["*.tf"]'
        # env:
        #   CDN: https://somecdn.com/...

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan