name: Deploy Resource Group Via Terraform

on:
  push:
    branches:
      - master

jobs:
  login-and-deploy-to-Azure:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_CREDENTIALS_AS_GITHUB_SECRET }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan