name: Deploy Azure Resources

on:
  push:
    branches:
      - master

jobs:
  deploy-to-Azure-with-Terraform:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["*.tf"]'
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          STORAGE_FOR_STATE_KEY: ${{ secrets.STORAGE_FOR_STATE_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve        