name: Deploy Resource Group Via Terraform

on:
  push:
    branches:
      - master

# env:
#   # AZURE_WEBAPP_NAME: csweb0619202
#   # AZURE_WEBAPP_PATH: '.'
#   # DOTNET_VERSION: '2.2.101'

jobs:
  login and deploy to Azure:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MY_CREDENTIALS_AS_GITHUB_SECRET }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        #with:
        #  cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init      
        
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: dotnet build + publish
      #   run: |
      #     dotnet build --configuration release
      #     dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PATH }}/myapp'
      
      # - name: Deploy to App Service
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     package: '${{ env.AZURE_WEBAPP_PATH }}/myapp'